language: cpp
addons:
  apt:
    packages:
    - build-essential
    - devscripts
    - debhelper
    - git-buildpackage
    - fakeroot
    - dput
install:
- echo -e "machine api.bintray.com\nlogin $BINTRAY_NAME\npassword $BINTRAY_TOKEN" >> ~/.netrc
- chmod go-rwx ~/.netrc
- echo "deb http://dl.bintray.com/jhermann/deb /" | sudo tee /etc/apt/sources.list.d/bintray-jhermann.list
- sudo apt-get update && sudo apt-get install -y -o "APT::Get::AllowUnauthenticated=yes" dput-webdav
- gpg --import galeksandrp.asc
- mv .dput.cf ~
- mv bintray.json ~
- git checkout $TRAVIS_BRANCH
- rm .travis.yml galeksandrp.asc*
- git add .
- git commit -m 'Removed .travis.yml to avoid conflicts with debian packaging'
deploy:
  skip_cleanup: true
  provider: script
  script: dput bintray ../pifm_1.0-1_amd64.changes
  on:
    all_branches: true
script:
- gbp buildpackage --git-debian-branch=$TRAVIS_BRANCH
before_install:
- openssl aes-256-cbc -K $encrypted_2267b8251b6f_key -iv $encrypted_2267b8251b6f_iv
  -in galeksandrp.asc.enc -out galeksandrp.asc -d
notifications:
  email: false
